server.port=8081
# Código de config inicial do Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/edenred_db
spring.datasource.username=postgres
spring.datasource.password=3456
spring.datasource.driver-class-name=org.postgresql.Driver

# Código para sempre criar/atualizar as tabelas automaticamente no Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true