server.port=8081
# Código de config inicial do Postgres
# spring.datasource.url=jdbc:postgresql://localhost:5432/edenred_db
# spring.datasource.username=postgres
# spring.datasource.password=3456
# spring.datasource.driver-class-name=org.postgresql.Driver

# # Código para sempre criar/atualizar as tabelas automaticamente no Postgres
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql=true

# ==================== H2 Database (para desenvolvimento) ====================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console do H2 (acesso no navegador)
spring.h2.console.enabled=true